version: 1.0.{build}
branches:
  only:
  - main
image: Visual Studio 2022
configuration: Debug
platform: x86
install:
- cmd: >-
    git clone https://github.com/microsoft/vcpkg

    cd vcpkg

    call bootstrap-vcpkg.bat

    vcpkg.exe integrate install

    vcpkg.exe install benchmark:x64-windows

    cd ..
clone_script:
- cmd: git clone https://github.com/SleepingSoul/intrinsics-benchmark
build:
  project: intrinsics-benchmark/intrinsics-benchmark/intrinsics-benchmark.sln
  parallel: true
  verbosity: normal